name: deable-serializer
services:
  app:
    type: php:7.0
    via: cli
tooling:
  composer:
    service: app
    description: Run Composer
    cmd: composer
  php:
    service: app
    description: Run PHP cli
    cmd: php
